### ISSUE TITLE
Github theme doesn't show Write and Preview buttons

### ISSUE THREAD

**Issue by dignajar** [pytesNET/tail.writer#5]
Hi,
I included the theme Github but for some reason is not loading the button Write and Preview. I don't have any error in the console (Browser inspect).

<img width="1162" alt="screenshot 2019-01-30 at 19 18 44" src="https://user-images.githubusercontent.com/507352/52010062-cb0ffc80-24d4-11e9-8076-56b68bfc7d3d.png">

The version is 0.3.2.

Regards

**Comment by SamBrishes** [comment]
Hellow,

thanks for your issue. The Preview function / button(s) are an optional feature, which requires [markedJS](https://github.com/markedjs/marked), as shown [on this jsFiddle](https://jsfiddle.net/SamBrishes/Lh64qyzf/3/). The tail.writer script itself doesn't contain any Markup parser.

I'm sorry, this is currently not mentioned in the `package.json` file and the current README file is really bad written. The next major release will complement that and should already be online, but I'm currently really busy.

Sincerely,
Sam.

**Comment by dignajar** [comment]
Perfect, I included the Marked script and works.
