### ISSUE TITLE
showdown is not defined

### ISSUE THREAD

**Issue by tigexplorer** [pytesNET/tail.writer#9]
Hi,
I've implemented tail.writer as follows:

In the Header
`<link type="text/css" rel="stylesheet" href="tail_writer/tail.writer-dark.css" />`

In the body, on top
`<script type="text/javascript" src="tail_writer/tail.writer-full.min.js"></script>`

In the body on bottom
`<script type="text/javascript">
            document.addEventListener("DOMContentLoaded", function(){
                tail.writer("textarea", { /* Your Options */ });
            });
        </script>`

The textarea is correct wrapped with the editor and the format options are working, 
except the toggle to markdown preview:

In the browser console I get this error
`showdown is not defined`

Also I get this in the browser console, also after copying this file in my tail_writer dir
```
Source-Map-Fehler: request failed with status 401
Source-Map-Adresse: tail.writer-dark.map
```
What may I'm doing wrong?

**Comment by SamBrishes** [comment]
Hellow,

thanks for your report.

the preview function requires an additional JavaScript library to work. It depends on the desired markup language, but for Markdown you need to embed either [marked](https://github.com/markedjs/marked) or [showdown](https://github.com/showdownjs/showdown).

Sincerely,
Sam.

**Comment by tigexplorer** [comment]
Ah, OK, sorry for the noise.
I loaded additionally showdown and it works fine:
`<script type="text/javascript" src="tail_writer/showdown.js"></script>`

Thanx for your very quick reply!

**Comment by SamBrishes** [comment]
Perfect, and no problem :D
